### ISSUE TITLE
Do I need to install reveal.js or other plugins?

### ISSUE THREAD

**Issue by MatthewPaulGithub** [mikitex70/redmine_reveal#2]
This seems like a really great idea. Tried to install but when I click to the wiki page I get an error -

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Can't see anything in the logs either.   You mention it uses reveal.js - do I need to install that prior to this plugin?  

Thanks!

**Comment by mikitex70** [comment]
No, @reveal.js@ is embedded with the plugin so you don't need to install it.
What is your configuration (version of Redmine, Ruby, OS)?

**Comment by MatthewPaulGithub** [comment]
It's probably a plugin interfering with it then, I have a ton of them -

System info: | Linux ip-172-30-0-237 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.1.10-p492 (2016-04-01) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Cvs                            1.12.13
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.3.0
  additionals                    2.0.3
  custom_menu                    1.7.4
  issue_charts                   1.3.0
  issue_hot_buttons              0.4.4
  projects_tree_view             0.0.8
  recurring_tasks                2.0.0-pre
  redmine__select2               1.1.0
  redmine_agile                  1.3.12
  redmine_base_deface            0.0.1
  redmine_custom_workflows       0.1.6
  redmine_customize_core_fields  1.0.0
  redmine_default_assign         0.6
  redmine_default_custom_query   1.2.0
  redmine_documents              1.0.0
  redmine_email_fetcher          0.3.1
  redmine_email_images           0.1.1
  redmine_email_inline_images    1.0.0
  redmine_image_clipboard_paste  3.3.0
  redmine_issue_tabs             1.2.2
  redmine_language_change        0.1.0
  redmine_lightbox2              0.3.2
  redmine_local_avatars          1.0.0
  redmine_my_page                0.1.10
  redmine_scm_extensions         0.4.0
  redmine_shady                  0.5.0
  redmine_silencer               0.4.1
  redmine_tab                    0.4.0
  redmine_theme_changer          0.2.0
  sidebar_hide                   0.0.7
  unread_issues                  1.5.0

It's a bitnami stack on an AWS VM.  No worries I'm building another template next week so I'll try it on a clean install to check if it's one of the other plugins.

**Comment by MatthewPaulGithub** [comment]
A bit more info on this. I fired up a new bitnami instance. Added some plugins and thought I'd try the reveal plugin again. At least this time I got a good error message.  This is after I install, and I click on WIKI and I get this error in the log -

Started GET "/projects/admin/wiki" for 73.85.254.89 at 2017-11-17 04:09:56 +0000
Processing by WikiController#show as HTML
  Parameters: {"project_id"=>"admin"}
Settings cache cleared.
  Current user: mpaul (id=6)
  Rendered attachments/_form.html.erb (3.9ms)
  Rendered wiki/edit.html.erb within layouts/base (11.3ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (2.8ms)
Completed 500 Internal Server Error in 52ms (ActiveRecord: 6.4ms)

ActionView::Template::Error (uninitialized constant PresentationViewListener::False):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: 
    18: <%= yield :header_tags -%>
    19: </head>
  plugins/redmine_reveal/lib/redmine_reveal/hooks/view_hooks.rb:49:in `lang_supported?'
  plugins/redmine_reveal/lib/redmine_reveal/hooks/view_hooks.rb:27:in `view_layouts_base_html_head'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___1954262517401504297_47371968027660'
  app/controllers/wiki_controller.rb:92:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


and my plugins in this instance are -

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Cvs                            1.12.13
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.0
  external_links_in_new_window   0.9
  issue_charts                   1.3.0
  issue_hot_buttons              0.4.4
  projects_tree_view             0.0.8
  recurring_tasks                2.0.0-pre
  redmine_agile                  1.4.5
  redmine_banner                 0.1.2
  redmine_custom_workflows       0.1.6
  redmine_default_assign         0.6
  redmine_email_fetcher          0.3.1
  redmine_image_clipboard_paste  3.3.0
  redmine_issue_tabs             1.2.2
  redmine_language_change        0.1.0
  redmine_lightbox2              0.3.2
  redmine_local_avatars          1.0.3
  redmine_mermaid_macro          0.0.1
  redmine_reveal                 0.1.0
  redmine_scm_extensions         0.4.0
  redmine_shady                  0.5.0
  redmine_silencer               0.4.1
  redmine_theme_changer          0.2.0
  sidebar_hide                   0.0.7
  unread_issues                  2.2.0


Again, not hassling you at all, I think your work is awesome, so I'm just posting this as an fyi.  Thanks again!
