### ISSUE TITLE
 macro button on the editor toolbar is not showing Markdown Text formatting

### ISSUE THREAD

**Issue by nicklesandy** [mikitex70/redmine_reveal#3]
Awesome plugins !!!

But how can I show macro button on toolbar for Markdown Text formatting, Please!

Administartion/Setting/Text formatting set to **Markdown** not **Textile**

**Comment by nicklesandy** [comment]
High-five!

**Comment by memachado** [comment]
I'm running into the same problem now.

Redmine version                4.2.3.stable

**Comment by mikitex70** [comment]
Give me some time, I'm a little busy but I think I should be able to fix it in a couple of days.
