### ISSUE TITLE
i cannot find the setup interface

### ISSUE THREAD

**Issue by perryjun** [mikitex70/redmine_reveal#8]
redmine 5.0.2 , i cannot find the setup interface

**Comment by mikitex70** [comment]
Hi @perryjun, what you means for "*i cannot find the setup interface*"?

**Comment by perryjun** [comment]
> Hi @perryjun, what you means for "_i cannot find the setup interface_"?

hi, i have found the tool bar when edit the wiki

**Comment by mikitex70** [comment]
No more feedback, I close the issue.
